CREATE TABLE OS_USERS(
    USR_ID INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(120) NOT NULL,
    USR_EMAIL VARCHAR(120) NOT NULL,
    USR_PHONE VARCHAR(120) NOT NULL,
    USR_PASSWORD VARCHAR(20) NOT NULL,
    PRIMARY KEY (USR_ID)
);



    
